GET  http://localhost:3000/employee
###s
POST http://localhost:3000/employee
Content-Type: application/json

{
    "firstname": "BALA",
    "lastname": "subscribe"
}
###s
GET  http://localhost:3000/employee/2
###s
DELETE   http://localhost:3000/employee/2